### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by marcinwysocki** [marcinwysocki/loadex#6]
Unfortunately there aren't any tests for Loadex right now. The reason for this is how this project was born - as an ad hoc solution, to a real-world, pressing issue - but for it to reach maturity, automated tests are mandatory.

**Comment by Ayoush** [comment]
Hey @marcinwysocki I am interested in writing test, but  since we don't have a documentation yet, can you just give me an overview of what is happening in **loadex.ex** file.

**Comment by marcinwysocki** [comment]
Hi @Ayoush, sorry for late reply, I've been quite busy this week. I think the best solution is to create a documentation first, I'll try to do it over the weekend.

**Comment by Ayoush** [comment]
Okay @marcinwysocki I might help you in that too if you would like to.

**Comment by marcinwysocki** [comment]
Thanks, I've just merged #7 with some basic docs for `Loadex`. If you'll find a way to improve them, please submit a PR. I hope I'll have more time to add more this week, but unfortunately I can't really promise...

**Comment by Ayoush** [comment]
Okay thanks @marcinwysocki

**Comment by marcinwysocki** [comment]
This is included in #8
